
version: "3.9"
services:
  marshal:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
      args:
        BUILD_ISMRMRD_FROM_SOURCE: "false"
        ISMRMRD_TAG: "v1.14.0"
    command: bash -lc "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j && ./build/marshal --http 0.0.0.0:8080 --ws 0.0.0.0:8090 --data /data"
    ports: ["8080:8080","8090:8090"]
    volumes: ["./data:/data", ".:/src"]
    working_dir: /src

  viz:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    command: bash -lc "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j && ./build/viz_client --ws ws://marshal:8090/ws --data /data"
    depends_on: ["marshal"]
    volumes: ["./data:/data", ".:/src"]
    working_dir: /src

  fk:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    command: bash -lc "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j && ./build/fk_client --http http://marshal:8080 --count 5 --step 0.05"
    depends_on: ["marshal"]
    volumes: [".:/src"]
    working_dir: /src
