FROM gcc:latest

# Create app directory
WORKDIR /app

# Copy all necessary files
COPY client-front-end.cpp file_routes.json httplib.h json.hpp ./

# Build client
RUN g++ client-front-end.cpp -o client-front-end -pthread

# Set default command (optional)
#CMD ["./client"]

COPY entrypoint-front-end.sh ./
CMD ["./entrypoint-front-end.sh"]