version: '3.3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: cpp_server
    ports:
      - "8080:8080"

  client-a:
    build:
      context: .
      dockerfile: Dockerfile.client-a
    container_name: cpp_client-a
    depends_on:
      - server

  client-b:
    build:
      context: .
      dockerfile: Dockerfile.client-b
    container_name: cpp_client-b
    depends_on:
      - server

  client-c:
    build:
      context: .
      dockerfile: Dockerfile.client-c
    container_name: cpp_client-c
    depends_on:
      - server
