FROM gcc:latest

# Create app directory
WORKDIR /app

# Copy source files
COPY server.cpp files.json file1.json file2.json file3.json httplib.h json.hpp circularBuffer.hpp ./

# Build server
RUN g++ server.cpp -o server -pthread

# Expose port for server
EXPOSE 8080

# Run server
CMD ["./server"]
