FROM gcc:latest

# Create app directory
WORKDIR /app

# Copy all necessary files
COPY client-c.cpp file_routes.json httplib.h json.hpp ./

# Build client
RUN g++ client-c.cpp -o client-c -pthread

# Set default command (optional)
#CMD ["./client"]

COPY entrypoint-c.sh ./
CMD ["./entrypoint-c.sh"]