FROM gcc:latest

# Create app directory
WORKDIR /app

# Copy all necessary files
COPY client-planning.cpp file_routes.json httplib.h json.hpp ./

# Build client
RUN g++ client-planning.cpp -o client-planning -pthread

# Set default command (optional)
#CMD ["./client"]

COPY entrypoint-planning.sh ./
RUN chmod +x entrypoint-planning.sh
CMD ["./entrypoint-planning.sh"]