FROM gcc:latest

# Create app directory
WORKDIR /app

# Copy source files
COPY server.cpp files.json httplib.h json.hpp circularBuffer.hpp ./
COPY  file1.json file2.json file3.json file_3D_images.json file_biological_signals.json file_catheter_base_configuration.json file_desired_plannned_motion.json file_forward_kinematics.json file_localization_data.json file_streaming_2D_images.json file_surface_model_parameters.json file_tip_position_orientation.json file_user_input.json /files/

# Build server
RUN g++ server.cpp -o server -pthread

# Expose port for server
EXPOSE 8080

# Run server
CMD ["./server"]
