FROM gcc:latest

# Create app directory
WORKDIR /app

# Copy all necessary files
COPY client-a.cpp file_routes.json httplib.h json.hpp ./

# Build client
RUN g++ client-a.cpp -o client-a -pthread

# Set default command (optional)
#CMD ["./client"]

COPY entrypoint-a.sh ./
CMD ["./entrypoint-a.sh"]