FROM gcc:latest

# Create app directory
WORKDIR /app

# Copy all necessary files
COPY client-force-sensor.cpp file_routes.json httplib.h json.hpp ./

# Build client
RUN g++ client-force-sensor.cpp -o client-force-sensor -pthread

# Set default command (optional)
#CMD ["./client"]

COPY entrypoint-force-sensor.sh ./
RUN chmod +x entrypoint-force-sensor.sh
CMD ["./entrypoint-force-sensor.sh"]