FROM gcc:latest

# Create app directory
WORKDIR /app

# Copy all necessary files
COPY client-catheter-tracking.cpp file_routes.json httplib.h json.hpp ./

# Build client
RUN g++ client-catheter-tracking.cpp -o client-catheter-tracking -pthread

# Set default command (optional)
#CMD ["./client"]

COPY entrypoint-catheter-tracking.sh ./
RUN chmod +x entrypoint-catheter-tracking.sh
CMD ["./entrypoint-catheter-tracking.sh"]