services:
  mri-marshal:
    image: cwru/mri-marshal:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.mri
      args:
        REPO_URL: https://github.com/cwru-mercis/cwru_data_marshal.git
        BRANCH: mri-data-marhsal
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - mri-data:/data

  robot-marshal:
    image: cwru/robot-marshal:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.robot
      args:
        REPO_URL: https://github.com/cwru-mercis/cwru_data_marshal.git
        BRANCH: robot_data_marshal_with_catheter_system_components
    ports:
      - "8081:8081"
    volumes:
      - robot-files:/files

volumes:
  mri-data:
  robot-files:
